# Site settings
title: IT notes
email: 
description: "Learning and practice new technologies."
baseurl: ""
url: "http://mike9251.github.io"
twitter_username: mike92p
github_username:  mike9251

# Build settings
markdown: kramdown
permalink: pretty

scope: '.highlight'

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
